// automatically generated by the FlatBuffers compiler, do not modify
// @generated
#![allow(unused_imports, dead_code)]
#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum CharacterAIExcelTableOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct CharacterAIExcelTable<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for CharacterAIExcelTable<'a> {
  type Inner = CharacterAIExcelTable<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> CharacterAIExcelTable<'a> {
  pub const VT_DATALIST: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    CharacterAIExcelTable { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CharacterAIExcelTableArgs<'args>
  ) -> flatbuffers::WIPOffset<CharacterAIExcelTable<'bldr>> {
    let mut builder = CharacterAIExcelTableBuilder::new(_fbb);
    let key = table_encryption_service::create_key(b"CharacterAIExcel");
      if let Some(x) = args.DataList {
        builder.add_DataList(x);
      }
    builder.finish()
  }

  pub fn unpack(&self) -> CharacterAIExcelTableT {
    let key = table_encryption_service::create_key(b"CharacterAIExcel");
    let DataList = self.DataList().map(|x| {
      x.iter().map(|t| t.unpack()).collect()
    });
    CharacterAIExcelTableT {
      DataList,
    }
  }

  #[inline]
  pub fn DataList(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<CharacterAIExcel<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<CharacterAIExcel>>>>(CharacterAIExcelTable::VT_DATALIST, None)}
  }
}

impl flatbuffers::Verifiable for CharacterAIExcelTable<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<CharacterAIExcel>>>>("DataList", Self::VT_DATALIST, false)?
     .finish();
    Ok(())
  }
}
pub struct CharacterAIExcelTableArgs<'a> {
    pub DataList: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<CharacterAIExcel<'a>>>>>,
}
impl<'a> Default for CharacterAIExcelTableArgs<'a> {
  #[inline]
  fn default() -> Self {
    CharacterAIExcelTableArgs {
      DataList: None,
    }
  }
}

impl Serialize for CharacterAIExcelTable<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("CharacterAIExcelTable", 1)?;
      if let Some(f) = self.DataList() {
        s.serialize_field("DataList", &f)?;
      } else {
        s.skip_field("DataList")?;
      }
    s.end()
  }
}

pub struct CharacterAIExcelTableBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> CharacterAIExcelTableBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_DataList(&mut self, DataList: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<CharacterAIExcel<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CharacterAIExcelTable::VT_DATALIST, DataList);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> CharacterAIExcelTableBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CharacterAIExcelTableBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<CharacterAIExcelTable<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for CharacterAIExcelTable<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("CharacterAIExcelTable");
      ds.field("DataList", &self.DataList());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct CharacterAIExcelTableT {
  pub DataList: Option<Vec<CharacterAIExcelT>>,
}
impl Default for CharacterAIExcelTableT {
  fn default() -> Self {
    Self {
      DataList: None,
    }
  }
}
impl CharacterAIExcelTableT {
  pub fn pack<'b, A: flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b, A>
  ) -> flatbuffers::WIPOffset<CharacterAIExcelTable<'b>> {
    let DataList = self.DataList.as_ref().map(|x|{
      let w: Vec<_> = x.iter().map(|t| t.pack(_fbb)).collect();_fbb.create_vector(&w)
    });
    CharacterAIExcelTable::create(_fbb, &CharacterAIExcelTableArgs{
      DataList,
    })
  }
}
