// automatically generated by the FlatBuffers compiler, do not modify
// @generated
#![allow(unused_imports, dead_code)]
#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum CharacterDialogEmojiExcelOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct CharacterDialogEmojiExcel<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for CharacterDialogEmojiExcel<'a> {
  type Inner = CharacterDialogEmojiExcel<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> CharacterDialogEmojiExcel<'a> {
  pub const VT_GROUPID: flatbuffers::VOffsetT = 4;
  pub const VT_TARGETINDEX: flatbuffers::VOffsetT = 6;
  pub const VT_DIALOGTYPE: flatbuffers::VOffsetT = 8;
  pub const VT_DURATION: flatbuffers::VOffsetT = 10;
  pub const VT_DURATIONKR: flatbuffers::VOffsetT = 12;
  pub const VT_HIDEUI: flatbuffers::VOffsetT = 14;
  pub const VT_LOCALIZEKR: flatbuffers::VOffsetT = 16;
  pub const VT_LOCALIZEJP: flatbuffers::VOffsetT = 18;
  pub const VT_LOCALIZETH: flatbuffers::VOffsetT = 20;
  pub const VT_LOCALIZETW: flatbuffers::VOffsetT = 22;
  pub const VT_LOCALIZEEN: flatbuffers::VOffsetT = 24;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    CharacterDialogEmojiExcel { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CharacterDialogEmojiExcelArgs<'args>
  ) -> flatbuffers::WIPOffset<CharacterDialogEmojiExcel<'bldr>> {
    let mut builder = CharacterDialogEmojiExcelBuilder::new(_fbb);
    let key = table_encryption_service::create_key(b"CharacterDialogEmoji");
      let x = args.DurationKr;
      let x = if table_encryption_service::use_encryption() { table_encryption_service::convert_long(x, &key) } else { x };
      builder.add_DurationKr(x);
      let x = args.Duration;
      let x = if table_encryption_service::use_encryption() { table_encryption_service::convert_long(x, &key) } else { x };
      builder.add_Duration(x);
      let x = args.GroupId;
      let x = if table_encryption_service::use_encryption() { table_encryption_service::convert_long(x, &key) } else { x };
      builder.add_GroupId(x);
      if let Some(x) = args.LocalizeEN {
        builder.add_LocalizeEN(x);
      }
      if let Some(x) = args.LocalizeTW {
        builder.add_LocalizeTW(x);
      }
      if let Some(x) = args.LocalizeTH {
        builder.add_LocalizeTH(x);
      }
      if let Some(x) = args.LocalizeJP {
        builder.add_LocalizeJP(x);
      }
      if let Some(x) = args.LocalizeKR {
        builder.add_LocalizeKR(x);
      }
      if let Some(x) = args.DialogType {
        builder.add_DialogType(x);
      }
      let x = args.TargetIndex;
      let x = if table_encryption_service::use_encryption() { table_encryption_service::convert_int(x, &key) } else { x };
      builder.add_TargetIndex(x);
      builder.add_HideUI(args.HideUI);
    builder.finish()
  }

  pub fn unpack(&self) -> CharacterDialogEmojiExcelT {
    let key = table_encryption_service::create_key(b"CharacterDialogEmoji");
      let GroupId = self.GroupId();
      let TargetIndex = self.TargetIndex();
    let DialogType = self.DialogType().map(|x| {
      if table_encryption_service::use_encryption() { table_encryption_service::convert_string(&x, &key).unwrap() } else { x.to_string() }
    });
      let Duration = self.Duration();
      let DurationKr = self.DurationKr();
      let HideUI = self.HideUI();
    let LocalizeKR = self.LocalizeKR().map(|x| {
      if table_encryption_service::use_encryption() { table_encryption_service::convert_string(&x, &key).unwrap() } else { x.to_string() }
    });
    let LocalizeJP = self.LocalizeJP().map(|x| {
      if table_encryption_service::use_encryption() { table_encryption_service::convert_string(&x, &key).unwrap() } else { x.to_string() }
    });
    let LocalizeTH = self.LocalizeTH().map(|x| {
      if table_encryption_service::use_encryption() { table_encryption_service::convert_string(&x, &key).unwrap() } else { x.to_string() }
    });
    let LocalizeTW = self.LocalizeTW().map(|x| {
      if table_encryption_service::use_encryption() { table_encryption_service::convert_string(&x, &key).unwrap() } else { x.to_string() }
    });
    let LocalizeEN = self.LocalizeEN().map(|x| {
      if table_encryption_service::use_encryption() { table_encryption_service::convert_string(&x, &key).unwrap() } else { x.to_string() }
    });
    CharacterDialogEmojiExcelT {
      GroupId,
      TargetIndex,
      DialogType,
      Duration,
      DurationKr,
      HideUI,
      LocalizeKR,
      LocalizeJP,
      LocalizeTH,
      LocalizeTW,
      LocalizeEN,
    }
  }

  #[inline]
  pub fn GroupId(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(CharacterDialogEmojiExcel::VT_GROUPID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn TargetIndex(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(CharacterDialogEmojiExcel::VT_TARGETINDEX, Some(0)).unwrap()}
  }
  #[inline]
  pub fn DialogType(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(CharacterDialogEmojiExcel::VT_DIALOGTYPE, None)}
  }
  #[inline]
  pub fn Duration(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(CharacterDialogEmojiExcel::VT_DURATION, Some(0)).unwrap()}
  }
  #[inline]
  pub fn DurationKr(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(CharacterDialogEmojiExcel::VT_DURATIONKR, Some(0)).unwrap()}
  }
  #[inline]
  pub fn HideUI(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(CharacterDialogEmojiExcel::VT_HIDEUI, Some(false)).unwrap()}
  }
  #[inline]
  pub fn LocalizeKR(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(CharacterDialogEmojiExcel::VT_LOCALIZEKR, None)}
  }
  #[inline]
  pub fn LocalizeJP(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(CharacterDialogEmojiExcel::VT_LOCALIZEJP, None)}
  }
  #[inline]
  pub fn LocalizeTH(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(CharacterDialogEmojiExcel::VT_LOCALIZETH, None)}
  }
  #[inline]
  pub fn LocalizeTW(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(CharacterDialogEmojiExcel::VT_LOCALIZETW, None)}
  }
  #[inline]
  pub fn LocalizeEN(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(CharacterDialogEmojiExcel::VT_LOCALIZEEN, None)}
  }
}

impl flatbuffers::Verifiable for CharacterDialogEmojiExcel<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i64>("GroupId", Self::VT_GROUPID, false)?
     .visit_field::<i32>("TargetIndex", Self::VT_TARGETINDEX, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("DialogType", Self::VT_DIALOGTYPE, false)?
     .visit_field::<i64>("Duration", Self::VT_DURATION, false)?
     .visit_field::<i64>("DurationKr", Self::VT_DURATIONKR, false)?
     .visit_field::<bool>("HideUI", Self::VT_HIDEUI, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("LocalizeKR", Self::VT_LOCALIZEKR, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("LocalizeJP", Self::VT_LOCALIZEJP, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("LocalizeTH", Self::VT_LOCALIZETH, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("LocalizeTW", Self::VT_LOCALIZETW, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("LocalizeEN", Self::VT_LOCALIZEEN, false)?
     .finish();
    Ok(())
  }
}
pub struct CharacterDialogEmojiExcelArgs<'a> {
    pub GroupId: i64,
    pub TargetIndex: i32,
    pub DialogType: Option<flatbuffers::WIPOffset<&'a str>>,
    pub Duration: i64,
    pub DurationKr: i64,
    pub HideUI: bool,
    pub LocalizeKR: Option<flatbuffers::WIPOffset<&'a str>>,
    pub LocalizeJP: Option<flatbuffers::WIPOffset<&'a str>>,
    pub LocalizeTH: Option<flatbuffers::WIPOffset<&'a str>>,
    pub LocalizeTW: Option<flatbuffers::WIPOffset<&'a str>>,
    pub LocalizeEN: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for CharacterDialogEmojiExcelArgs<'a> {
  #[inline]
  fn default() -> Self {
    CharacterDialogEmojiExcelArgs {
      GroupId: 0,
      TargetIndex: 0,
      DialogType: None,
      Duration: 0,
      DurationKr: 0,
      HideUI: false,
      LocalizeKR: None,
      LocalizeJP: None,
      LocalizeTH: None,
      LocalizeTW: None,
      LocalizeEN: None,
    }
  }
}

impl Serialize for CharacterDialogEmojiExcel<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("CharacterDialogEmojiExcel", 11)?;
      s.serialize_field("GroupId", &self.GroupId())?;
      s.serialize_field("TargetIndex", &self.TargetIndex())?;
      if let Some(f) = self.DialogType() {
        s.serialize_field("DialogType", &f)?;
      } else {
        s.skip_field("DialogType")?;
      }
      s.serialize_field("Duration", &self.Duration())?;
      s.serialize_field("DurationKr", &self.DurationKr())?;
      s.serialize_field("HideUI", &self.HideUI())?;
      if let Some(f) = self.LocalizeKR() {
        s.serialize_field("LocalizeKR", &f)?;
      } else {
        s.skip_field("LocalizeKR")?;
      }
      if let Some(f) = self.LocalizeJP() {
        s.serialize_field("LocalizeJP", &f)?;
      } else {
        s.skip_field("LocalizeJP")?;
      }
      if let Some(f) = self.LocalizeTH() {
        s.serialize_field("LocalizeTH", &f)?;
      } else {
        s.skip_field("LocalizeTH")?;
      }
      if let Some(f) = self.LocalizeTW() {
        s.serialize_field("LocalizeTW", &f)?;
      } else {
        s.skip_field("LocalizeTW")?;
      }
      if let Some(f) = self.LocalizeEN() {
        s.serialize_field("LocalizeEN", &f)?;
      } else {
        s.skip_field("LocalizeEN")?;
      }
    s.end()
  }
}

pub struct CharacterDialogEmojiExcelBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> CharacterDialogEmojiExcelBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_GroupId(&mut self, GroupId: i64) {
    self.fbb_.push_slot::<i64>(CharacterDialogEmojiExcel::VT_GROUPID, GroupId, 0);
  }
  #[inline]
  pub fn add_TargetIndex(&mut self, TargetIndex: i32) {
    self.fbb_.push_slot::<i32>(CharacterDialogEmojiExcel::VT_TARGETINDEX, TargetIndex, 0);
  }
  #[inline]
  pub fn add_DialogType(&mut self, DialogType: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CharacterDialogEmojiExcel::VT_DIALOGTYPE, DialogType);
  }
  #[inline]
  pub fn add_Duration(&mut self, Duration: i64) {
    self.fbb_.push_slot::<i64>(CharacterDialogEmojiExcel::VT_DURATION, Duration, 0);
  }
  #[inline]
  pub fn add_DurationKr(&mut self, DurationKr: i64) {
    self.fbb_.push_slot::<i64>(CharacterDialogEmojiExcel::VT_DURATIONKR, DurationKr, 0);
  }
  #[inline]
  pub fn add_HideUI(&mut self, HideUI: bool) {
    self.fbb_.push_slot::<bool>(CharacterDialogEmojiExcel::VT_HIDEUI, HideUI, false);
  }
  #[inline]
  pub fn add_LocalizeKR(&mut self, LocalizeKR: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CharacterDialogEmojiExcel::VT_LOCALIZEKR, LocalizeKR);
  }
  #[inline]
  pub fn add_LocalizeJP(&mut self, LocalizeJP: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CharacterDialogEmojiExcel::VT_LOCALIZEJP, LocalizeJP);
  }
  #[inline]
  pub fn add_LocalizeTH(&mut self, LocalizeTH: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CharacterDialogEmojiExcel::VT_LOCALIZETH, LocalizeTH);
  }
  #[inline]
  pub fn add_LocalizeTW(&mut self, LocalizeTW: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CharacterDialogEmojiExcel::VT_LOCALIZETW, LocalizeTW);
  }
  #[inline]
  pub fn add_LocalizeEN(&mut self, LocalizeEN: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CharacterDialogEmojiExcel::VT_LOCALIZEEN, LocalizeEN);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> CharacterDialogEmojiExcelBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CharacterDialogEmojiExcelBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<CharacterDialogEmojiExcel<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for CharacterDialogEmojiExcel<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("CharacterDialogEmojiExcel");
      ds.field("GroupId", &self.GroupId());
      ds.field("TargetIndex", &self.TargetIndex());
      ds.field("DialogType", &self.DialogType());
      ds.field("Duration", &self.Duration());
      ds.field("DurationKr", &self.DurationKr());
      ds.field("HideUI", &self.HideUI());
      ds.field("LocalizeKR", &self.LocalizeKR());
      ds.field("LocalizeJP", &self.LocalizeJP());
      ds.field("LocalizeTH", &self.LocalizeTH());
      ds.field("LocalizeTW", &self.LocalizeTW());
      ds.field("LocalizeEN", &self.LocalizeEN());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct CharacterDialogEmojiExcelT {
  pub GroupId: i64,
  pub TargetIndex: i32,
  pub DialogType: Option<String>,
  pub Duration: i64,
  pub DurationKr: i64,
  pub HideUI: bool,
  pub LocalizeKR: Option<String>,
  pub LocalizeJP: Option<String>,
  pub LocalizeTH: Option<String>,
  pub LocalizeTW: Option<String>,
  pub LocalizeEN: Option<String>,
}
impl Default for CharacterDialogEmojiExcelT {
  fn default() -> Self {
    Self {
      GroupId: 0,
      TargetIndex: 0,
      DialogType: None,
      Duration: 0,
      DurationKr: 0,
      HideUI: false,
      LocalizeKR: None,
      LocalizeJP: None,
      LocalizeTH: None,
      LocalizeTW: None,
      LocalizeEN: None,
    }
  }
}
impl CharacterDialogEmojiExcelT {
  pub fn pack<'b, A: flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b, A>
  ) -> flatbuffers::WIPOffset<CharacterDialogEmojiExcel<'b>> {
    let GroupId = self.GroupId;
    let TargetIndex = self.TargetIndex;
    let DialogType = self.DialogType.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let Duration = self.Duration;
    let DurationKr = self.DurationKr;
    let HideUI = self.HideUI;
    let LocalizeKR = self.LocalizeKR.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let LocalizeJP = self.LocalizeJP.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let LocalizeTH = self.LocalizeTH.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let LocalizeTW = self.LocalizeTW.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let LocalizeEN = self.LocalizeEN.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    CharacterDialogEmojiExcel::create(_fbb, &CharacterDialogEmojiExcelArgs{
      GroupId,
      TargetIndex,
      DialogType,
      Duration,
      DurationKr,
      HideUI,
      LocalizeKR,
      LocalizeJP,
      LocalizeTH,
      LocalizeTW,
      LocalizeEN,
    })
  }
}
