// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Global
{

using global::System;
using global::System.Collections.Generic;
using global::Kuroko.Crypto;
using global::Google.FlatBuffers;

public struct InformationStrategyObjectExcelTable : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static InformationStrategyObjectExcelTable GetRootAsInformationStrategyObjectExcelTable(ByteBuffer _bb) { return GetRootAsInformationStrategyObjectExcelTable(_bb, new InformationStrategyObjectExcelTable()); }
  public static InformationStrategyObjectExcelTable GetRootAsInformationStrategyObjectExcelTable(ByteBuffer _bb, InformationStrategyObjectExcelTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public InformationStrategyObjectExcelTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Global.InformationStrategyObjectExcel? DataList(int j) { int o = __p.__offset(4); return o != 0 ? (Global.InformationStrategyObjectExcel?)(new Global.InformationStrategyObjectExcel()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DataListLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Global.InformationStrategyObjectExcelTable> CreateInformationStrategyObjectExcelTable(FlatBufferBuilder builder,
      VectorOffset DataListOffset = default(VectorOffset)) {
    builder.StartTable(1);
    InformationStrategyObjectExcelTable.AddDataList(builder, DataListOffset);
    return InformationStrategyObjectExcelTable.EndInformationStrategyObjectExcelTable(builder);
  }

  public static void StartInformationStrategyObjectExcelTable(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDataList(FlatBufferBuilder builder, VectorOffset dataListOffset) { builder.AddOffset(0, dataListOffset.Value, 0); }
  public static VectorOffset CreateDataListVector(FlatBufferBuilder builder, Offset<Global.InformationStrategyObjectExcel>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDataListVectorBlock(FlatBufferBuilder builder, Offset<Global.InformationStrategyObjectExcel>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataListVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Global.InformationStrategyObjectExcel>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataListVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Global.InformationStrategyObjectExcel>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDataListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Global.InformationStrategyObjectExcelTable> EndInformationStrategyObjectExcelTable(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Global.InformationStrategyObjectExcelTable>(o);
  }
  public InformationStrategyObjectExcelTableT UnPack() {
    var _o = new InformationStrategyObjectExcelTableT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(InformationStrategyObjectExcelTableT _o) {
		byte[] key = TableEncryptionService.CreateKey("InformationStrategyObjectExcel");
    _o.DataList = new List<Global.InformationStrategyObjectExcelT>();
    for (var _j = 0; _j < this.DataListLength; ++_j) {_o.DataList.Add(this.DataList(_j).HasValue ? this.DataList(_j).Value.UnPack() : null);}
  }
  public static Offset<Global.InformationStrategyObjectExcelTable> Pack(FlatBufferBuilder builder, InformationStrategyObjectExcelTableT _o) {
    if (_o == null) return default(Offset<Global.InformationStrategyObjectExcelTable>);
		byte[] key = TableEncryptionService.CreateKey("InformationStrategyObjectExcel");
    var _DataList = default(VectorOffset);
    if (_o.DataList != null) {
      var __DataList = new Offset<Global.InformationStrategyObjectExcel>[_o.DataList.Count];
      for (var _j = 0; _j < __DataList.Length; ++_j) { __DataList[_j] = Global.InformationStrategyObjectExcel.Pack(builder, _o.DataList[_j]); }
      _DataList = CreateDataListVector(builder, __DataList);
    }
    return CreateInformationStrategyObjectExcelTable(
      builder,
      _DataList);
  }
}

public class InformationStrategyObjectExcelTableT
{
  public List<Global.InformationStrategyObjectExcelT> DataList { get; set; }

  public InformationStrategyObjectExcelTableT() {
    this.DataList = null;
  }
}


static public class InformationStrategyObjectExcelTableVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*DataList*/, Global.InformationStrategyObjectExcelVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
