// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Japan
{

using global::System;
using global::System.Collections.Generic;
using global::Kuroko.Crypto;
using global::Google.FlatBuffers;

public struct CharacterStatsTransExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CharacterStatsTransExcel GetRootAsCharacterStatsTransExcel(ByteBuffer _bb) { return GetRootAsCharacterStatsTransExcel(_bb, new CharacterStatsTransExcel()); }
  public static CharacterStatsTransExcel GetRootAsCharacterStatsTransExcel(ByteBuffer _bb, CharacterStatsTransExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterStatsTransExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Japan.StatType TransSupportStats { get { int o = __p.__offset(4); return o != 0 ? (Japan.StatType)__p.bb.GetInt(o + __p.bb_pos) : Japan.StatType.None; } }
  public Japan.EchelonExtensionType EchelonExtensionType { get { int o = __p.__offset(6); return o != 0 ? (Japan.EchelonExtensionType)__p.bb.GetInt(o + __p.bb_pos) : Japan.EchelonExtensionType.Base; } }
  public int TransSupportStatsFactor { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public Japan.StatTransType StatTransType { get { int o = __p.__offset(10); return o != 0 ? (Japan.StatTransType)__p.bb.GetInt(o + __p.bb_pos) : Japan.StatTransType.SpecialTransStat; } }

  public static Offset<Japan.CharacterStatsTransExcel> CreateCharacterStatsTransExcel(FlatBufferBuilder builder,
      Japan.StatType TransSupportStats = Japan.StatType.None,
      Japan.EchelonExtensionType EchelonExtensionType = Japan.EchelonExtensionType.Base,
      int TransSupportStatsFactor = 0,
      Japan.StatTransType StatTransType = Japan.StatTransType.SpecialTransStat) {
    builder.StartTable(4);
    CharacterStatsTransExcel.AddStatTransType(builder, StatTransType);
    CharacterStatsTransExcel.AddTransSupportStatsFactor(builder, TransSupportStatsFactor);
    CharacterStatsTransExcel.AddEchelonExtensionType(builder, EchelonExtensionType);
    CharacterStatsTransExcel.AddTransSupportStats(builder, TransSupportStats);
    return CharacterStatsTransExcel.EndCharacterStatsTransExcel(builder);
  }

  public static void StartCharacterStatsTransExcel(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddTransSupportStats(FlatBufferBuilder builder, Japan.StatType transSupportStats) { builder.AddInt(0, (int)transSupportStats, 0); }
  public static void AddEchelonExtensionType(FlatBufferBuilder builder, Japan.EchelonExtensionType echelonExtensionType) { builder.AddInt(1, (int)echelonExtensionType, 0); }
  public static void AddTransSupportStatsFactor(FlatBufferBuilder builder, int transSupportStatsFactor) { builder.AddInt(2, transSupportStatsFactor, 0); }
  public static void AddStatTransType(FlatBufferBuilder builder, Japan.StatTransType statTransType) { builder.AddInt(3, (int)statTransType, 0); }
  public static Offset<Japan.CharacterStatsTransExcel> EndCharacterStatsTransExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Japan.CharacterStatsTransExcel>(o);
  }
  public CharacterStatsTransExcelT UnPack() {
    var _o = new CharacterStatsTransExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CharacterStatsTransExcelT _o) {
		byte[] key = TableEncryptionService.CreateKey("CharacterStatsTrans");
    _o.TransSupportStats = TableEncryptionService.UseEncryption ? (Japan.StatType)TableEncryptionService.Convert((int)this.TransSupportStats, key) : this.TransSupportStats;
    _o.EchelonExtensionType = TableEncryptionService.UseEncryption ? (Japan.EchelonExtensionType)TableEncryptionService.Convert((int)this.EchelonExtensionType, key) : this.EchelonExtensionType;
    _o.TransSupportStatsFactor = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert((int)this.TransSupportStatsFactor, key) : this.TransSupportStatsFactor;
    _o.StatTransType = TableEncryptionService.UseEncryption ? (Japan.StatTransType)TableEncryptionService.Convert((int)this.StatTransType, key) : this.StatTransType;
  }
  public static Offset<Japan.CharacterStatsTransExcel> Pack(FlatBufferBuilder builder, CharacterStatsTransExcelT _o) {
    if (_o == null) return default(Offset<Japan.CharacterStatsTransExcel>);
		byte[] key = TableEncryptionService.CreateKey("CharacterStatsTrans");
		var _TransSupportStats = TableEncryptionService.UseEncryption ? (Japan.StatType)TableEncryptionService.Convert((int)_o.TransSupportStats, key) : _o.TransSupportStats;
		var _EchelonExtensionType = TableEncryptionService.UseEncryption ? (Japan.EchelonExtensionType)TableEncryptionService.Convert((int)_o.EchelonExtensionType, key) : _o.EchelonExtensionType;
		var _TransSupportStatsFactor = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert((int)_o.TransSupportStatsFactor, key) : _o.TransSupportStatsFactor;
		var _StatTransType = TableEncryptionService.UseEncryption ? (Japan.StatTransType)TableEncryptionService.Convert((int)_o.StatTransType, key) : _o.StatTransType;
    return CreateCharacterStatsTransExcel(
      builder,
      TableEncryptionService.UseEncryption ? _TransSupportStats : _o.TransSupportStats,
      TableEncryptionService.UseEncryption ? _EchelonExtensionType : _o.EchelonExtensionType,
      TableEncryptionService.UseEncryption ? _TransSupportStatsFactor : _o.TransSupportStatsFactor,
      TableEncryptionService.UseEncryption ? _StatTransType : _o.StatTransType);
  }
}

public class CharacterStatsTransExcelT
{
  public Japan.StatType TransSupportStats { get; set; }
  public Japan.EchelonExtensionType EchelonExtensionType { get; set; }
  public int TransSupportStatsFactor { get; set; }
  public Japan.StatTransType StatTransType { get; set; }

  public CharacterStatsTransExcelT() {
    this.TransSupportStats = Japan.StatType.None;
    this.EchelonExtensionType = Japan.EchelonExtensionType.Base;
    this.TransSupportStatsFactor = 0;
    this.StatTransType = Japan.StatTransType.SpecialTransStat;
  }
}


static public class CharacterStatsTransExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*TransSupportStats*/, 4 /*Japan.StatType*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*EchelonExtensionType*/, 4 /*Japan.EchelonExtensionType*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*TransSupportStatsFactor*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*StatTransType*/, 4 /*Japan.StatTransType*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
