// automatically generated by the FlatBuffers compiler, do not modify
// @generated
#![allow(unused_imports, dead_code)]
#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum EventContentClueSearchExcelOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EventContentClueSearchExcel<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for EventContentClueSearchExcel<'a> {
  type Inner = EventContentClueSearchExcel<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> EventContentClueSearchExcel<'a> {
  pub const VT_EVENTCONTENTID: flatbuffers::VOffsetT = 4;
  pub const VT_TITLELOCALIZE: flatbuffers::VOffsetT = 6;
  pub const VT_USEPREFABNAME: flatbuffers::VOffsetT = 8;
  pub const VT_CLUEBGIMAGEPATH: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    EventContentClueSearchExcel { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EventContentClueSearchExcelArgs<'args>
  ) -> flatbuffers::WIPOffset<EventContentClueSearchExcel<'bldr>> {
    let mut builder = EventContentClueSearchExcelBuilder::new(_fbb);
    let key = table_encryption_service::create_key(b"EventContentClueSearch");
      let x = args.EventContentId;
      let x = if table_encryption_service::use_encryption() { table_encryption_service::convert_long(x, &key) } else { x };
      builder.add_EventContentId(x);
      if let Some(x) = args.ClueBGImagePath {
        builder.add_ClueBGImagePath(x);
      }
      if let Some(x) = args.UsePrefabName {
        builder.add_UsePrefabName(x);
      }
      let x = args.TitleLocalize;
      let x = if table_encryption_service::use_encryption() { table_encryption_service::convert_uint(x, &key) } else { x };
      builder.add_TitleLocalize(x);
    builder.finish()
  }

  pub fn unpack(&self) -> EventContentClueSearchExcelT {
    let key = table_encryption_service::create_key(b"EventContentClueSearch");
      let EventContentId = self.EventContentId();
      let TitleLocalize = self.TitleLocalize();
    let UsePrefabName = self.UsePrefabName().map(|x| {
      if table_encryption_service::use_encryption() { table_encryption_service::convert_string(&x, &key).unwrap() } else { x.to_string() }
    });
    let ClueBGImagePath = self.ClueBGImagePath().map(|x| {
      if table_encryption_service::use_encryption() { table_encryption_service::convert_string(&x, &key).unwrap() } else { x.to_string() }
    });
    EventContentClueSearchExcelT {
      EventContentId,
      TitleLocalize,
      UsePrefabName,
      ClueBGImagePath,
    }
  }

  #[inline]
  pub fn EventContentId(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(EventContentClueSearchExcel::VT_EVENTCONTENTID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn TitleLocalize(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(EventContentClueSearchExcel::VT_TITLELOCALIZE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn UsePrefabName(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(EventContentClueSearchExcel::VT_USEPREFABNAME, None)}
  }
  #[inline]
  pub fn ClueBGImagePath(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(EventContentClueSearchExcel::VT_CLUEBGIMAGEPATH, None)}
  }
}

impl flatbuffers::Verifiable for EventContentClueSearchExcel<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i64>("EventContentId", Self::VT_EVENTCONTENTID, false)?
     .visit_field::<u32>("TitleLocalize", Self::VT_TITLELOCALIZE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("UsePrefabName", Self::VT_USEPREFABNAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("ClueBGImagePath", Self::VT_CLUEBGIMAGEPATH, false)?
     .finish();
    Ok(())
  }
}
pub struct EventContentClueSearchExcelArgs<'a> {
    pub EventContentId: i64,
    pub TitleLocalize: u32,
    pub UsePrefabName: Option<flatbuffers::WIPOffset<&'a str>>,
    pub ClueBGImagePath: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for EventContentClueSearchExcelArgs<'a> {
  #[inline]
  fn default() -> Self {
    EventContentClueSearchExcelArgs {
      EventContentId: 0,
      TitleLocalize: 0,
      UsePrefabName: None,
      ClueBGImagePath: None,
    }
  }
}

impl Serialize for EventContentClueSearchExcel<'_> {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    let mut s = serializer.serialize_struct("EventContentClueSearchExcel", 4)?;
      s.serialize_field("EventContentId", &self.EventContentId())?;
      s.serialize_field("TitleLocalize", &self.TitleLocalize())?;
      if let Some(f) = self.UsePrefabName() {
        s.serialize_field("UsePrefabName", &f)?;
      } else {
        s.skip_field("UsePrefabName")?;
      }
      if let Some(f) = self.ClueBGImagePath() {
        s.serialize_field("ClueBGImagePath", &f)?;
      } else {
        s.skip_field("ClueBGImagePath")?;
      }
    s.end()
  }
}

pub struct EventContentClueSearchExcelBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> EventContentClueSearchExcelBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_EventContentId(&mut self, EventContentId: i64) {
    self.fbb_.push_slot::<i64>(EventContentClueSearchExcel::VT_EVENTCONTENTID, EventContentId, 0);
  }
  #[inline]
  pub fn add_TitleLocalize(&mut self, TitleLocalize: u32) {
    self.fbb_.push_slot::<u32>(EventContentClueSearchExcel::VT_TITLELOCALIZE, TitleLocalize, 0);
  }
  #[inline]
  pub fn add_UsePrefabName(&mut self, UsePrefabName: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(EventContentClueSearchExcel::VT_USEPREFABNAME, UsePrefabName);
  }
  #[inline]
  pub fn add_ClueBGImagePath(&mut self, ClueBGImagePath: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(EventContentClueSearchExcel::VT_CLUEBGIMAGEPATH, ClueBGImagePath);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> EventContentClueSearchExcelBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EventContentClueSearchExcelBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<EventContentClueSearchExcel<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for EventContentClueSearchExcel<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("EventContentClueSearchExcel");
      ds.field("EventContentId", &self.EventContentId());
      ds.field("TitleLocalize", &self.TitleLocalize());
      ds.field("UsePrefabName", &self.UsePrefabName());
      ds.field("ClueBGImagePath", &self.ClueBGImagePath());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct EventContentClueSearchExcelT {
  pub EventContentId: i64,
  pub TitleLocalize: u32,
  pub UsePrefabName: Option<String>,
  pub ClueBGImagePath: Option<String>,
}
impl Default for EventContentClueSearchExcelT {
  fn default() -> Self {
    Self {
      EventContentId: 0,
      TitleLocalize: 0,
      UsePrefabName: None,
      ClueBGImagePath: None,
    }
  }
}
impl EventContentClueSearchExcelT {
  pub fn pack<'b, A: flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b, A>
  ) -> flatbuffers::WIPOffset<EventContentClueSearchExcel<'b>> {
    let EventContentId = self.EventContentId;
    let TitleLocalize = self.TitleLocalize;
    let UsePrefabName = self.UsePrefabName.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let ClueBGImagePath = self.ClueBGImagePath.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    EventContentClueSearchExcel::create(_fbb, &EventContentClueSearchExcelArgs{
      EventContentId,
      TitleLocalize,
      UsePrefabName,
      ClueBGImagePath,
    })
  }
}
