// automatically generated by the FlatBuffers compiler, do not modify
// @generated
#![allow(unused_imports, dead_code)]
#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
extern crate serde;
use self::serde::ser::{Serialize, Serializer, SerializeStruct};
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_PRODUCT_DISPLAY_TAG: i32 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_PRODUCT_DISPLAY_TAG: i32 = 5;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_PRODUCT_DISPLAY_TAG: [ProductDisplayTag; 6] = [
  ProductDisplayTag::None,
  ProductDisplayTag::New,
  ProductDisplayTag::Hot,
  ProductDisplayTag::Sale,
  ProductDisplayTag::Limited,
  ProductDisplayTag::Free,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct ProductDisplayTag(pub i32);
#[allow(non_upper_case_globals)]
impl ProductDisplayTag {
  pub const None: Self = Self(0);
  pub const New: Self = Self(1);
  pub const Hot: Self = Self(2);
  pub const Sale: Self = Self(3);
  pub const Limited: Self = Self(4);
  pub const Free: Self = Self(5);

  pub const ENUM_MIN: i32 = 0;
  pub const ENUM_MAX: i32 = 5;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::None,
    Self::New,
    Self::Hot,
    Self::Sale,
    Self::Limited,
    Self::Free,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::None => Some("None"),
      Self::New => Some("New"),
      Self::Hot => Some("Hot"),
      Self::Sale => Some("Sale"),
      Self::Limited => Some("Limited"),
      Self::Free => Some("Free"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for ProductDisplayTag {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl Serialize for ProductDisplayTag {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
  where
    S: Serializer,
  {
    serializer.serialize_unit_variant("ProductDisplayTag", self.0 as u32, self.variant_name().unwrap())
  }
}

impl<'a> flatbuffers::Follow<'a> for ProductDisplayTag {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<i32>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for ProductDisplayTag {
    type Output = ProductDisplayTag;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<i32>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for ProductDisplayTag {
  type Scalar = i32;
  #[inline]
  fn to_little_endian(self) -> i32 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i32) -> Self {
    let b = i32::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for ProductDisplayTag {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    i32::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for ProductDisplayTag {}
