name: Generate Flatbuffers (C#)

on:
  schedule:
    - cron: '0 3 * * 2,4'
    - cron: '0 5 * * 2,4'
    - cron: '0 7 * * 2,4'
    - cron: '0 9 * * 2,4'
  
  workflow_dispatch:

jobs:
  generate:
    runs-on: macos-15
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Switch to flatdata-cs branch
        run: |
          git checkout -B flatdata-cs

      - name: Download latest release
        run: |
          curl -L -o bafb-macos-aarch64.zip https://github.com/Deathemonic/BA-FB/releases/latest/download/bafb-macos-aarch64.zip

      - name: Extract executable
        run: |
          unzip bafb-macos-aarch64.zip
          chmod +x bafb

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Clean previous data
        run: |
          find . -name ".git" -prune -o -name "bafb" -prune -o -name "*.zip" -prune -o -type f -exec rm {} +
          find . -name ".git" -prune -o -name "bafb" -prune -o -type d -empty -delete 2>/dev/null || true

      - name: Create config file
        run: |
          cat > config.toml << EOF
          [flatc]
          url = "${{ secrets.FLATC_URL_MAC_ARM }}"
          EOF

      - name: Download Japan FBS
        run: |
          curl -o japan.fbs https://raw.githubusercontent.com/Deathemonic/BA-FB/refs/heads/data/Japan/BlueArchive.fbs

      - name: Download Global FBS
        run: |
          curl -o global.fbs https://raw.githubusercontent.com/Deathemonic/BA-FB/refs/heads/data/Global/BlueArchive.fbs

      - name: Generate Japan Flatbuffers
        run: |
          ./bafb generate --fbs japan.fbs --language c-sharp --output ./

      - name: Generate Global Flatbuffers
        run: |
          ./bafb generate --fbs global.fbs --language c-sharp --output ./

      - name: Clean up executable and zip file
        run: |
          rm -f bafb bafb-macos-aarch64.zip japan.fbs global.fbs config.toml

      - name: Commit and push changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git commit -m "Update generated flatbuffers - $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin flatdata-cs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
